### ISSUE TITLE
[Glassfish logs] java.io.FileNotFoundException warnings

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1036]
On 2.0 and dev versions
- PWC6351: In TLD scanning, the supplied resource file:/var/lib/payara/domains/docdokuplm/applications/docdoku-server-ear/lib/ridl.jar does not exist
- PWC6351: In TLD scanning, the supplied resource file:/var/lib/payara/domains/docdokuplm/applications/docdoku-server-ear/lib/unoloader.jar does not exist
- PWC6351: In TLD scanning, the supplied resource file:/var/lib/payara/domains/docdokuplm/applications/docdoku-server-ear/lib/jurt.jar does not exist

Here is the full stack trace:
https://gist.github.com/elisabelgenereux/847dec70d59ada744256ac2fe14736e7#file-filenotfoundexception_warnings

**Comment by wermut** [comment]
Had same problem with nightly 2.5 from 27.09.2016

ridl and jurt exist in directory but with version number. Making a softlink of them to ridl.jar and jurt.jar helps. The OpenOffice unoloader.jar does not exist at all. Wrong maven url and config?

**Comment by jzanon** [comment]
- These 3 JAR are declared in MANIFEST.MF of Apache OpenOffice libraries: `jurt` and `juh`.
- These 2 libraries are needed by JodConverter library.
- This library is base of module : https://github.com/polarsys/eplmp/tree/master/eplmp-server/eplmp-server-office-doc which uses `jodconverter` to manipulate OpenOffice.
- These 3 JAR are embedded into /lib folder of EAR.

**No fix found for now, but:** last version of jodconverter (a maintained one) shall be used instead of a local beta version directly embedded in source code.

Proposed alternative: https://github.com/sbraconnier/jodconverter

**Comment by Hunsu** [comment]
I think the issue is in Payara as the jars are available n the lib folder.  Payara doesn't append the jar version to the filename so it doesn't find them.

**Comment by florentgarin** [comment]
The problem comes because inside the jar file juh-3.2.1.jar (jurt also) the manifest has a ClassPath entry which references ridl.jar (at the same folder level).
But ridl.jar cannot be found as the jar file is named ridl-3.2.1.jar.

That's it.
To fix that we should remove that indication from the manifest file. Moreover it's a bad and outdated practice to manage the classpath from the manifest file. But those jar are not ours, that the biggest problem....

**Comment by mguimard** [comment]
Solution brought by @jzanon seems to be the only and best one.
