### ISSUE TITLE
[Advanced search] Attributes search broken

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#702]
and LOV selection is not correctly displayed

**Comment by mguimard** [comment]
Works for me if I search for an attribute. Please provide an example

**Comment by elisabelgenereux** [comment]
the remaining bug is on LOV attribute

**Comment by mguimard** [comment]
Works for TEXT, NUMBER, and BOOLEAN types.
For URLs, it's broken because the url is missing a "/" in ESSearcher (eg: http:/www.foo.com)
For Dates, we need to harmonize the behavior. Creation dates are stored as : "2015-07-06T13:58:15.000Z", whereas attributes are stored as "Mon Jul 06 02:00:00 CEST 2015"
