### ISSUE TITLE
[Readonly user] can delete a part

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#937]
from the parts list

**Comment by kelto** [comment]
Since we can put ACL on a part, what should be the behaviour here. Should the user be able to delete a part if he only has Read Access on workspace but full access on the part ?

**Comment by florentgarin** [comment]
I think the answer should be yes even if that could be strange. But since the user, in such case, can modify it, there is no reason why deletion and modification should be treat differently.

So that leads to to the fact that we should, on the workspace administration page, know what objects (documents and parts) have upgraded rights.
Moreover we should probably only allow the workspace administrator to upgrade rights to a workspace read only user.

**Comment by kelto** [comment]
#971 
#972
